'''
SNAKE WATER AND GUN IS A VARIATION OF CHILDREN'S GAME 'rock-paper-scissors' WHERE PLAYER USE HAND GESTURE
TO REPRESENT A SNAKE, WATER, OR A GUN. THE GUN BEATS THE SNAKE, THE WATER BEATS THE GUN AND SNAKE BEATS
WATER .

WRITE A PYTHON PROGRAM TO CREATE A SNAKE WATER GUN GAME IN PYTHON USING IF-ELSE SATEMENT. DO NOT CREATE ANY
FANCY GUI . USE PROPER FUNCTION TO CHEK THE WIN.

               S   W    G
computer =     -1  0    1
player   = S   D   Win  L
           W   L   D    Win
           G   W   L    D
'''
